version: "3.9"
services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "traefiknet"
  spawner:
    image: "spawner:latest"
    container_name: "spawner"
    ports:
      - "8008:8008"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "traefiknet"
    command: ./spawner  -cookie-fallback-url='http://localhost/home' -traefik-check-enabled=true
    environment:
      - GIN_MODE=release
    labels:
      traefik.enable: "true"
      traefik.http.routers.spawner.entrypoints: "web"
      traefik.http.routers.spawner.rule: "PathPrefix(`/`)"
      traefik.http.services.spawner.loadbalancer.server.port: 8000
  mock-home:
    image: "mock-home:latest"
    container_name: "mock-home"
    networks:
      - "traefiknet"
    environment:
      - GIN_MODE=release
    labels:
      traefik.enable: "true"
      traefik.http.routers.mock-home.entrypoints: "web"
      traefik.http.routers.mock-home.rule: "PathPrefix(`/home`)"
      traefik.http.services.mock-home.loadbalancer.server.port: 8000
networks:
  traefiknet:
    name: traefiknet
    attachable: true
