version: "3.9"
services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "traefiknet"
  spawner:
    image: "spawner:latest"
    container_name: "spawner"
    ports:
      - "8008:8008"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "traefiknet"
        #    command: ./spawner -container-prefix=''
    
    labels:
      traefik.enable: "true"
      traefik.http.routers.spawner.entrypoints: "web"
      traefik.http.routers.spawner.rule: "PathPrefix(`/`)"
      traefik.http.routers.spawner.middlewares: "spawner-context"
      traefik.http.middlewares.spawner-context.redirectregex.regex: "^http://localhost/deploy(.*)"
      traefik.http.middlewares.spawner-context.redirectregex.replacement: "http://localhost/"
networks:
  traefiknet:
    name: traefiknet
    attachable: true
