version: "3.9"
services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure  
      - --entrypoints.web.http.redirections.entrypoint.scheme=https  
      - --entrypoints.web.forwardedHeaders.insecure=true
      - --entrypoints.websecure.forwardedHeaders.insecure=true
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-config/:/configuration/"
    networks:
      - "traefiknet"
  spawner:
    image: "spawner:latest"
    container_name: "spawner"
    ports:
      - "8008:8008"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "traefiknet"
    command: ./spawner -cookie-fallback-url='https://localhost/home' -traefik-check-enabled=true
    environment:
      - GIN_MODE=debug
    labels:
      traefik.enable: "true"
      traefik.http.routers.spawner.entrypoints: "websecure"
      traefik.http.routers.spawner.rule: "PathPrefix(`/`)"
      traefik.http.services.spawner.loadbalancer.server.port: 8000
      traefik.http.routers.spawner.tls: true
  mock-home:
    image: "mock-home:latest"
    container_name: "mock-home"
    networks:
      - "traefiknet"
    environment:
      - GIN_MODE=debug
    labels:
      traefik.enable: "true"
      traefik.http.routers.mock-home.entrypoints: "websecure"
      traefik.http.routers.mock-home.rule: "PathPrefix(`/home`)"
      traefik.http.routers.mock-home.priority: 99
      traefik.http.services.mock-home.loadbalancer.server.port: 8000
      traefik.http.routers.mock-home.tls: true
networks:
  traefiknet:
    name: traefiknet
    attachable: true
